# Generated by Django 4.0.1 on 2022-01-25 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Наименование группы')),
                ('number_of_students', models.IntegerField(verbose_name='Количество студентов')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('fist_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('date_of_birt', models.DateField(verbose_name='Дата рождения')),
                ('series', models.CharField(max_length=5, verbose_name='Серия паспорта')),
                ('number', models.IntegerField(verbose_name='Номер паспорта')),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.groups', verbose_name='Группа')),
            ],
        ),
    ]
