# Generated by Django 4.0.1 on 2022-01-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='date_of_birt',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
