# Generated by Django 4.0.1 on 2022-01-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_rename_date_of_birt_students_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'ordering': ['name'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['last_name', 'date_of_birth'], 'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterField(
            model_name='students',
            name='number',
            field=models.CharField(max_length=6, verbose_name='Номер паспорта'),
        ),
    ]
